Improve API Documentation
ractf/core pull request #36
Opened 2020-10-03 16:14 UTC by JoshHeng

Improves #8:
- Updates `djangorestframework` to `3.12.1` to add new OpenAPI3 functionality
- Adds description to all endpoints
- Tag all endpoints

![image](https://user-images.githubusercontent.com/34946235/94996306-c4843300-059b-11eb-8e4c-cd3743a16beb.png)

2020-10-03 16:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ractf/core?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ractf/core?pullRequest=36) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: Bottersnike<br/>:white_check_mark: Bentechy66<br/>:white_check_mark: david-cooke<br/>:x: JoshHeng<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ractf/core?pullRequest=36) it.</sub>

2020-10-03 16:19 UTC, JoshHeng commented
It seems like I accidently forked from `master` instead of `refactor2` - is this ok?

2020-10-04 22:01 UTC, david-cooke requested changes
If you've done this off the wrong branch, I'm not convinced how mergeable it will be, could you open a new pr based off the right branch?

2020-10-05 21:37 UTC, JoshHeng commented
See #44 for correct branch PR

2020-10-05 21:37 UTC, closed without merging