Improve API Documentation
ractf/core pull request #44
Opened 2020-10-05 21:36 UTC by JoshHeng

Improves #8:
- Updates djangorestframework to 3.12.1 to add new OpenAPI3 functionality
- Adds description to all endpoints
- Tags all endpoints

Same as #36 but commits cherry picked off refactor2 branch

2020-10-05 22:42 UTC, david-cooke requested changes
Looks good to me once a couple things are cleaned up

2020-10-05 22:42 UTC, david-cooke commented on src/authentication/views.py
> +    Promote a user to sudo
That's not what this view does, when an admin hits this view, it will make their token impersonate a given user.

2020-10-05 22:42 UTC, david-cooke commented on src/authentication/views.py
> +    Demote a user from sudo
See above, this does the opposite, it stops the impersonation.

2020-10-05 22:42 UTC, david-cooke commented on src/challenge/views.py
> +    Vote for a challenge
IMO this is a bit unclear, the users aren't voting for a challenge as such, they're voting on whether they liked the challenge.

2020-10-05 22:42 UTC, david-cooke commented on src/challengeserver/views.py
> +    Get system information.
Probably worth clarifying, this is getting the system info of the andromeda node, not the box. Also, worth noting for us to investigate at a later point - how does andromeda in docker handle sysinfo, I don't think its going to be at all accurate.

2020-10-05 22:42 UTC, david-cooke commented on src/config/views.py
> +    def get(self, request, name):
I don't know how I feel about this change, I'm not convinced of the benefit of separating these out, I feel like theres a django rest framework abstraction to handle this case but idk. A more major issue that is actually blocking the merge is that this is vulnerable to CVE-2020-15235, you can skid the patch from https://github.com/ractf/core/commit/f3dc89b9f6ab1544a289b3efc06699b13d63e0bd

2020-10-05 22:56 UTC, thebeanogamer requested changes
I agree with @david-cooke, this is really good. Only thing from my side is that my Poetry is complaining that the lockfile is out of date, fix that and it's all good by me.

2020-10-06 17:23 UTC, JoshHeng commented on src/config/views.py
> +    def get(self, request, name):
The problem I was facing is that generateschema complained when there were multiple url patterns with the same view (as they had the same operation ID).

If you think they should still be merged I could try and sort something out?

2020-10-06 21:56 UTC, thebeanogamer approved these changes

2020-10-07 12:36 UTC, Bentechy66 approved these changes

2020-10-08 14:26 UTC, david-cooke approved these changes

2020-10-08 14:26 UTC, merged