Migrate to Python 3.9
ractf/core pull request #51
Opened 2020-10-08 22:59 UTC by thebeanogamer

2020-10-08 23:00 UTC, david-cooke commented
have you actually tested this?

2020-10-08 23:00 UTC, thebeanogamer commented
Of course not

2020-10-08 23:00 UTC, thebeanogamer commented
And that's why we have CI

2020-10-08 23:00 UTC, david-cooke approved these changes

2020-10-08 23:03 UTC, david-cooke requested changes
I'm not merging this until CI passes

2020-10-08 23:05 UTC, thebeanogamer commented
Good thing the CI is required then.

The issue appears to be upstream. Sad!

2020-10-08 23:06 UTC, david-cooke commented
I have a feeling it'll be broken because upstream for quite a while

2020-10-08 23:12 UTC, Bentechy66 requested changes
no

2020-12-26 14:36 UTC, closed without merging

2020-12-27 18:48 UTC, david-cooke commented
how could you close such a well written contribution