Complex Unlocking Criteria
ractf/core pull request #68
Opened 2021-01-30 02:21 UTC by Bentechy66

Switches out the `unlocks` field for a `unlock_requirements` field, which takes Reverse Polish Notation(tm) of challenge IDs, supporting AND and OR queries.

2021-01-30 02:23 UTC, david-cooke commented
ractf - now with turing complete challenge unlocks

2021-01-30 02:48 UTC, thebeanogamer reviewed
0/10, not enough use of `exec()`

2021-01-30 03:18 UTC, david-cooke commented
see earlier comment, no stack based vms except java are allowed to run on ix420

2021-01-30 03:19 UTC, Bentechy66 commented
ayayay

2021-01-30 03:25 UTC, david-cooke requested changes
For this to be production ready, its going to need support for XOR, NAND, NOR and XNOR.

2021-01-30 03:26 UTC, david-cooke commented
I would also like to see a more versatile instruction set however once the bare minimum is covered, we can figure the rest out from there

2021-01-30 03:26 UTC, david-cooke commented
tl;dr if it isnt an rce vuln its not powerful enough

2021-01-30 15:03 UTC, david-cooke commented
you literally added lootboxes to the api then refuse to add xor to challenge unlocking

2021-01-31 18:51 UTC, 404dcd approved these changes
LGTM

2021-01-31 18:56 UTC, AmusedNetwork requested changes
Change this commit title and we can get it merged.

2021-02-23 01:29 UTC, david-cooke approved these changes
LGTM

2021-02-23 01:30 UTC, merged