more tests
ractf/core pull request #76
Opened 2021-02-26 18:18 UTC by Bentechy66

2021-02-26 18:19 UTC, thebeanogamer requested changes
Why are you making these changes to `__init__.py`?

2021-02-26 18:24 UTC, thebeanogamer commented
:+1: 86% coverage

2021-02-27 01:23 UTC, thebeanogamer approved these changes

2021-02-27 01:33 UTC, david-cooke approved these changes

2021-02-27 01:33 UTC, merged