fix
ractf/core pull request #98
Opened 2021-04-20 15:02 UTC by Bentechy66

2021-04-20 15:07 UTC, thebeanogamer approved these changes
:shrug:

2021-04-20 15:26 UTC, jerbob reviewed
I'm not sure this is the right approach to a solution for this.
I've just done some light googling and this looks promising:
https://github.com/korfuri/django-prometheus/blob/master/documentation/exports.md#exporting-metrics-in-a-wsgi-application-with-multiple-processes-per-processhttps://echorand.me/posts/python-prometheus-monitoring-options/
I'd much rather we stuck with the existing framework's approaches over adding in tech debt that we'll inevitably remove once we figure out how to better utilise django-prometheus.

I will have a look at implementing this tonight if needed, the docs above should give us plenty to experiment with for now.

2021-04-20 16:32 UTC, thebeanogamer commented
> I'm not sure this is the right approach to a solution for this.
> I've just done some light googling and this looks promising:
> https://github.com/korfuri/django-prometheus/blob/master/documentation/exports.md#exporting-metrics-in-a-wsgi-application-with-multiple-processes-per-process
> I'd much rather we stuck with the existing framework's approaches over adding in tech debt that we'll inevitably remove once we figure out how to better utilise django-prometheus.
> 
> I will have a look at implementing this tonight if needed, the docs above should give us plenty to experiment with for now.

This looks really messy, exposing on another port already makes routing through Traefik kinda a pain (and they want to do a range for some mad reason), then unlike @Bentechy66's solution we'd still have the issue where statistics are not consistent between Gunicorn and Daphne.

2021-04-20 16:34 UTC, thebeanogamer commented
Furthermore, putting the stats into Redis means we can horizontally scale core, whereas keeping it in the context of a worker prevents that.

2021-04-20 16:39 UTC, thebeanogamer commented
@Bentechy66 is this cache written to Postgres, or will we lose stats on Redis restarting?

2021-04-20 18:50 UTC, jerbob commented
> @Bentechy66 is this cache written to Postgres, or will we lose stats on Redis restarting?
We will lose stats if redis is restarted while core is still running with this approach, yes.

2021-04-20 18:51 UTC, thebeanogamer commented
To be fair, I think we still do at the moment, and if we're scraping to prometheus it doesn't matter.

2021-04-20 18:59 UTC, jerbob requested changes

2021-04-20 18:59 UTC, jerbob commented on src/stats/signals.py
> +from django.core.cache import caches
You should be using the default cache here:
```suggestion
from django.core.cache import cache
```

2021-04-20 18:59 UTC, jerbob commented on src/stats/signals.py
> +cache = caches["default"]
```suggestion
```

2021-04-20 18:59 UTC, jerbob commented on src/stats/views.py
> +from django.core.cache import caches
```suggestion
from django.core.cache import cache
```

2021-04-20 18:59 UTC, jerbob commented on src/stats/views.py
> +    cache = caches["default"]
```suggestion
```

2021-04-21 20:59 UTC, david-cooke approved these changes
This is a horrible hack but its more fixed than it is now

2021-04-21 21:05 UTC, merged